name: Crawl GitHub Stars (demo)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'repos.csv' # prevents infinite loop when CSV is updated

jobs:
  crawl:
    if: github.actor != 'github-actions[bot]' # prevents bot retrigger
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to commit and push updates

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Wait for Postgres to be ready
        run: |
          for i in $(seq 1 20); do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 1
          done

      - name: Setup Postgres schema
        env:
          PGPASSWORD: postgres
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          psql -h localhost -U postgres -d postgres -f schema.sql

      - name: Run crawler (Node)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        run: node crawler.js

      - name: Dump DB to CSV
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d postgres -c "\copy (SELECT github_id, full_name, html_url, stars, crawled_at FROM repos) TO 'repos.csv' CSV HEADER"

      - name: Commit and push CSV to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repos.csv
          git diff --quiet && echo "No changes to commit" || (git commit -m "Update crawled repos data [skip ci]" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: github-crawl-results
          path: repos.csv
